version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'spacecrafter'
      MYSQL_USER: 'devuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: spccrafter_api:dev
    environment:
      FLASK_ENV: 'dev'
      DEV_DB_NAME: 'spacecrafter'
      DEV_DB_USER: 'devuser'
      DEV_DB_PASSWORD: 'password'
      DEV_DB_HOST: 'db'
      DEV_DB_PORT: '3306'
      JWT_SECRET_KEY: 'B7CnCaKdLVHHJgTek2_xY6PoiKHOixzzPyQDPowv7FA'
    ports:
      - "5050:5050"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: