version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'spacecrafter'
      MYSQL_USER: 'devuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    image: spccrafter_api:dev
    environment:
      FLASK_ENV: 'dev'
      DEV_DB_NAME: 'spacecrafter'
      DEV_DB_USER: 'devuser'
      DEV_DB_PASSWORD: 'password'
      DEV_DB_HOST: 'db'
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  mysql_data: